# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'theme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_theme(object):
    def setupUi(self, theme):
        theme.setObjectName("theme")
        theme.resize(511, 292)
        self.gridLayoutWidget = QtWidgets.QWidget(theme)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.reset = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 5, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.info = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 3, 1, 1, 1)
        self.image = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 3, 1, 1)
        self.color = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.color.setObjectName("color")
        self.gridLayout.addWidget(self.color, 1, 1, 1, 1)
        self.ok = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        self.choose = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.choose.setObjectName("choose")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.gridLayout.addWidget(self.choose, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 6, 2, 1, 1)

        self.retranslateUi(theme)
        QtCore.QMetaObject.connectSlotsByName(theme)

    def retranslateUi(self, theme):
        _translate = QtCore.QCoreApplication.translate
        theme.setWindowTitle(_translate("theme", "主题设置"))
        self.reset.setText(_translate("theme", "重置主题"))
        self.info.setText(_translate("theme", "预设主题"))
        self.image.setText(_translate("theme", "图片主题"))
        self.color.setText(_translate("theme", "颜色主题"))
        self.ok.setText(_translate("theme", "确认"))
        self.choose.setItemText(0, _translate("theme", "彩霞"))
        self.choose.setItemText(1, _translate("theme", "棕色"))
        self.choose.setItemText(2, _translate("theme", "绿色海滩"))
        self.choose.setItemText(3, _translate("theme", "红蓝"))
        self.choose.setItemText(4, _translate("theme", "地平线"))
